'use client';
import { Download, SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { CATEGORIES, defaultFilters, type ObservationFilters, type ClassifiedEvent } from '@/lib/classification';
import { exportObservations } from '@/lib/export-observations';
export default function ClassificationControls({filters,onChange,events,sample,onRetry}:{filters:ObservationFilters;onChange:(f:ObservationFilters)=>void;events:ClassifiedEvent[];sample:boolean;onRetry:()=>void}) {
  const active=filters.category!=='all'||filters.minFrp!==''||filters.maxFrp!==''||filters.dayNight!=='all'||filters.highIndustrial;
  const invalid=filters.minFrp!==''&&filters.maxFrp!==''&&Number(filters.minFrp)>Number(filters.maxFrp);
  const download=(format:'csv'|'geojson')=>{const url=URL.createObjectURL(new Blob([exportObservations(events,format,sample)],{type:format==='csv'?'text/csv;charset=utf-8':'application/geo+json'}));const a=document.createElement('a');a.href=url;a.download=`thermowatch-${sample?'sample':'classified'}-${new Date().toISOString().slice(0,10)}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <Popover><PopoverTrigger asChild><Button variant="outline" aria-label="Classification filters and export"><SlidersHorizontal />Filters{active?' •':''}</Button></PopoverTrigger><PopoverContent align="end" className="classification-filters"><h3>Filter observations</h3><label htmlFor="category-filter">Classification</label><Select value={filters.category} onValueChange={value=>onChange({...filters,category:value as ObservationFilters['category']})}><SelectTrigger id="category-filter"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All classifications</SelectItem>{Object.entries(CATEGORIES).map(([key,c])=><SelectItem key={key} value={key}>{c.label}</SelectItem>)}</SelectContent></Select><div className="frp-inputs"><div><label htmlFor="frp-min">Min FRP · MW</label><Input id="frp-min" type="number" min="0" step="any" placeholder="0" value={filters.minFrp} onChange={e=>onChange({...filters,minFrp:e.target.value})} /></div><div><label htmlFor="frp-max">Max FRP · MW</label><Input id="frp-max" type="number" min="0" step="any" placeholder="No limit" value={filters.maxFrp} onChange={e=>onChange({...filters,maxFrp:e.target.value})} /></div></div>{invalid&&<p role="alert">Maximum FRP must be at least the minimum.</p>}<label htmlFor="day-night-filter">Day / night</label><Select value={filters.dayNight} onValueChange={value=>onChange({...filters,dayNight:value as ObservationFilters['dayNight']})}><SelectTrigger id="day-night-filter"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Day and night</SelectItem><SelectItem value="D">Day</SelectItem><SelectItem value="N">Night</SelectItem></SelectContent></Select><label className="industrial-check"><Checkbox checked={filters.highIndustrial} onCheckedChange={v=>onChange({...filters,highIndustrial:v===true})} />Industrial related · rule confidence ≥80%</label><p>Includes industrial fire, persistent sources and mining. Scores are uncalibrated.</p><div className="filter-buttons"><Button variant="ghost" size="sm" onClick={()=>onChange({...defaultFilters})}>Reset filters</Button>{!sample&&<Button variant="ghost" size="sm" onClick={onRetry}>Retry enrichment</Button>}</div><div className="export-actions"><span>Export {events.length.toLocaleString()} visible records</span><div><Button variant="outline" size="sm" disabled={!events.length||invalid} onClick={()=>download('csv')}><Download />CSV</Button><Button variant="outline" size="sm" disabled={!events.length||invalid} onClick={()=>download('geojson')}><Download />GeoJSON</Button></div></div></PopoverContent></Popover>;
}
