import { CATEGORIES, RULE_VERSION } from './classification.ts';
import type { ClassifiedEvent } from './classification';
export function exportObservations(events:ClassifiedEvent[],format:'csv'|'geojson',sample:boolean) {
  const rows=events.map(e=>({id:e.id,latitude:e.latitude,longitude:e.longitude,detected_at:e.detected_at,satellite:e.satellite,source:e.source,frp_mw:e.frp,brightness_i4_k:e.brightness_ti4,brightness_i5_k:e.brightness_ti5,day_night:e.day_night,firms_confidence:e.confidence,classification:CATEGORIES[e.classification.category].label,subtype:e.classification.subtype??'',rule_confidence_percent:e.classification.confidence,confidence_meaning:'Uncalibrated rule support; not probability',facility:e.classification.context?.facility?.name??'',facility_distance_m:e.classification.context?.facility?.distance_m??null,facility_osm_url:e.classification.context?.facility?.osm_url??'',land_cover:e.classification.context?.land_cover??'unmapped',context_status:e.classification.context?.status??'pending',context_source:e.classification.context?.source??'',context_checked_at:e.classification.context?.fetched_at??'',context_limitations:e.classification.context?.note??'',history_status:e.classification.persistence?.status??'pending',earlier_active_days:e.classification.persistence?.days??null,history_source:e.classification.persistence?.source??'',baseline_frp_mw:e.classification.persistence?.baseline_frp??null,reasoning:e.classification.reasons.join(' '),rule_version:RULE_VERSION,synthetic_sample:sample,export_scope:'Currently visible loaded observations; not a global census'}));
  if(format==='geojson')return JSON.stringify({type:'FeatureCollection',metadata:{exported_at:new Date().toISOString(),scope:'Visible loaded observations',synthetic_sample:sample,attribution:'NASA FIRMS; © OpenStreetMap contributors (ODbL)',rule_version:RULE_VERSION},features:rows.map(row=>({type:'Feature',id:row.id,geometry:{type:'Point',coordinates:[row.longitude,row.latitude]},properties:row}))},null,2);
  const cell=(value:unknown)=>{let s=value==null?'':String(value);if(typeof value==='string'&&/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
  const keys=Object.keys(rows[0]??{id:'',classification:''});
  return [keys.map(cell).join(','),...rows.map(row=>keys.map(k=>cell(row[k as keyof typeof row])).join(','))].join('\r\n');
}
